# Generated by Django 3.1.3 on 2020-11-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20201121_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
