# Generated by Django 3.1.3 on 2020-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_moviecomment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='score',
            field=models.FloatField(),
        ),
    ]
